{
  "timestamp": "2025-10-25T20:19:05.229696",
  "files_processed": [],
  "vulnerabilities": [],
  "total_packages": 0,
  "errors": [
    {
      "file": "services/requirements/ml.txt",
      "error": "  ERROR: Could not find a version that satisfies the requirement torch==2.1.0 (from versions: 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 2.5.0, 2.5.1, 2.6.0, 2.7.0, 2.7.1, 2.8.0, 2.9.0)\nTraceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/resolvelib/resolvers.py\", line 397, in resolve\n    self._add_to_criteria(self.state.criteria, r, parent=None)\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/resolvelib/resolvers.py\", line 174, in _add_to_criteria\n    raise RequirementsConflicted(criterion)\npip._vendor.resolvelib.resolvers.RequirementsConflicted: Requirements conflict: SpecifierRequirement('torch==2.1.0')\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py\", line 95, in resolve\n    result = self._result = resolver.resolve(\n                            ^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/resolvelib/resolvers.py\", line 546, in resolve\n    state = resolution.resolve(requirements, max_rounds=max_rounds)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/resolvelib/resolvers.py\", line 399, in resolve\n    raise ResolutionImpossible(e.criterion.information)\npip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('torch==2.1.0'), parent=None)]\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/runner/.local/bin/pip-compile\", line 8, in <module>\n    sys.exit(cli())\n             ^^^^^\n  File \"/usr/lib/python3/dist-packages/click/core.py\", line 1157, in __call__\n    return self.main(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/click/core.py\", line 1078, in main\n    rv = self.invoke(ctx)\n         ^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/click/core.py\", line 1434, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/click/core.py\", line 783, in invoke\n    return __callback(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/click/decorators.py\", line 33, in new_func\n    return f(get_current_context(), *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/.local/lib/python3.12/site-packages/piptools/scripts/compile.py\", line 479, in cli\n    results = resolver.resolve(max_rounds=max_rounds)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/.local/lib/python3.12/site-packages/piptools/resolver.py\", line 635, in resolve\n    is_resolved = self._do_resolve(\n                  ^^^^^^^^^^^^^^^^^\n  File \"/home/runner/.local/lib/python3.12/site-packages/piptools/resolver.py\", line 670, in _do_resolve\n    resolver.resolve(\n  File \"/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py\", line 104, in resolve\n    raise error from e\npip._internal.exceptions.DistributionNotFound: No matching distribution found for torch==2.1.0\n"
    },
    {
      "file": "services/requirements/base.txt",
      "error": "Traceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/urllib3/response.py\", line 438, in _error_catcher\n    yield\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/urllib3/response.py\", line 561, in read\n    data = self._fp_read(amt) if not fp_closed else b\"\"\n           ^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/urllib3/response.py\", line 527, in _fp_read\n    return self._fp.read(amt) if amt is not None else self._fp.read()\n                                                      ^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/http/client.py\", line 473, in read\n    return self._read_chunked(amt)\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/http/client.py\", line 595, in _read_chunked\n    while (chunk_left := self._get_chunk_left()) is not None:\n                         ^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/http/client.py\", line 579, in _get_chunk_left\n    chunk_left = self._read_next_chunk_size()\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/http/client.py\", line 539, in _read_next_chunk_size\n    line = self.fp.readline(_MAXLINE + 1)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/socket.py\", line 707, in readinto\n    return self._sock.recv_into(b)\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/ssl.py\", line 1252, in recv_into\n    return self.read(nbytes, buffer)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/ssl.py\", line 1104, in read\n    return self._sslobj.read(len, buffer)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTimeoutError: The read operation timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/.local/bin/pip-compile\", line 8, in <module>\n    sys.exit(cli())\n             ^^^^^\n  File \"/usr/lib/python3/dist-packages/click/core.py\", line 1157, in __call__\n    return self.main(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/click/core.py\", line 1078, in main\n    rv = self.invoke(ctx)\n         ^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/click/core.py\", line 1434, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/click/core.py\", line 783, in invoke\n    return __callback(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/click/decorators.py\", line 33, in new_func\n    return f(get_current_context(), *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/.local/lib/python3.12/site-packages/piptools/scripts/compile.py\", line 479, in cli\n    results = resolver.resolve(max_rounds=max_rounds)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/.local/lib/python3.12/site-packages/piptools/resolver.py\", line 635, in resolve\n    is_resolved = self._do_resolve(\n                  ^^^^^^^^^^^^^^^^^\n  File \"/home/runner/.local/lib/python3.12/site-packages/piptools/resolver.py\", line 670, in _do_resolve\n    resolver.resolve(\n  File \"/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py\", line 95, in resolve\n    result = self._result = resolver.resolve(\n                            ^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/resolvelib/resolvers.py\", line 546, in resolve\n    state = resolution.resolve(requirements, max_rounds=max_rounds)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/resolvelib/resolvers.py\", line 397, in resolve\n    self._add_to_criteria(self.state.criteria, r, parent=None)\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/resolvelib/resolvers.py\", line 173, in _add_to_criteria\n    if not criterion.candidates:\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/resolvelib/structs.py\", line 156, in __bool__\n    return bool(self._sequence)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py\", line 155, in __bool__\n    return any(self)\n           ^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py\", line 143, in <genexpr>\n    return (c for c in iterator if id(c) not in self._incompatible_ids)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py\", line 44, in _iter_built\n    for version, func in infos:\n  File \"/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/factory.py\", line 297, in iter_index_candidate_infos\n    result = self._finder.find_best_candidate(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py\", line 890, in find_best_candidate\n    candidates = self.find_all_candidates(project_name)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py\", line 831, in find_all_candidates\n    page_candidates = list(page_candidates_it)\n                      ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/index/sources.py\", line 194, in page_candidates\n    yield from self._candidates_from_page(self._link)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py\", line 791, in process_project_url\n    index_response = self._link_collector.fetch_response(project_url)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/index/collector.py\", line 461, in fetch_response\n    return _get_index_content(location, session=self.session)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/index/collector.py\", line 364, in _get_index_content\n    resp = _get_simple_response(url, session=session)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/index/collector.py\", line 135, in _get_simple_response\n    resp = session.get(\n           ^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/requests/sessions.py\", line 602, in get\n    return self.request(\"GET\", url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/network/session.py\", line 520, in request\n    return super().request(method, url, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/requests/sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/requests/sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/cachecontrol/adapter.py\", line 76, in send\n    resp = super().send(request, stream, timeout, verify, cert, proxies)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/requests/adapters.py\", line 538, in send\n    return self.build_response(request, resp)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/cachecontrol/adapter.py\", line 117, in build_response\n    response.read(decode_content=False)\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/urllib3/response.py\", line 560, in read\n    with self._error_catcher():\n  File \"/usr/lib/python3.12/contextlib.py\", line 158, in __exit__\n    self.gen.throw(value)\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/urllib3/response.py\", line 443, in _error_catcher\n    raise ReadTimeoutError(self._pool, None, \"Read timed out.\")\npip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='pypi.org', port=443): Read timed out.\n"
    },
    {
      "file": "services/requirements/data.txt",
      "error": "Traceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/urllib3/response.py\", line 438, in _error_catcher\n    yield\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/urllib3/response.py\", line 561, in read\n    data = self._fp_read(amt) if not fp_closed else b\"\"\n           ^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/urllib3/response.py\", line 527, in _fp_read\n    return self._fp.read(amt) if amt is not None else self._fp.read()\n                                                      ^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/http/client.py\", line 473, in read\n    return self._read_chunked(amt)\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/http/client.py\", line 595, in _read_chunked\n    while (chunk_left := self._get_chunk_left()) is not None:\n                         ^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/http/client.py\", line 579, in _get_chunk_left\n    chunk_left = self._read_next_chunk_size()\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/http/client.py\", line 539, in _read_next_chunk_size\n    line = self.fp.readline(_MAXLINE + 1)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/socket.py\", line 707, in readinto\n    return self._sock.recv_into(b)\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/ssl.py\", line 1252, in recv_into\n    return self.read(nbytes, buffer)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/ssl.py\", line 1104, in read\n    return self._sslobj.read(len, buffer)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTimeoutError: The read operation timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/.local/bin/pip-compile\", line 8, in <module>\n    sys.exit(cli())\n             ^^^^^\n  File \"/usr/lib/python3/dist-packages/click/core.py\", line 1157, in __call__\n    return self.main(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/click/core.py\", line 1078, in main\n    rv = self.invoke(ctx)\n         ^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/click/core.py\", line 1434, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/click/core.py\", line 783, in invoke\n    return __callback(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/click/decorators.py\", line 33, in new_func\n    return f(get_current_context(), *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/.local/lib/python3.12/site-packages/piptools/scripts/compile.py\", line 479, in cli\n    results = resolver.resolve(max_rounds=max_rounds)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/.local/lib/python3.12/site-packages/piptools/resolver.py\", line 635, in resolve\n    is_resolved = self._do_resolve(\n                  ^^^^^^^^^^^^^^^^^\n  File \"/home/runner/.local/lib/python3.12/site-packages/piptools/resolver.py\", line 670, in _do_resolve\n    resolver.resolve(\n  File \"/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py\", line 95, in resolve\n    result = self._result = resolver.resolve(\n                            ^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/resolvelib/resolvers.py\", line 546, in resolve\n    state = resolution.resolve(requirements, max_rounds=max_rounds)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/resolvelib/resolvers.py\", line 397, in resolve\n    self._add_to_criteria(self.state.criteria, r, parent=None)\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/resolvelib/resolvers.py\", line 173, in _add_to_criteria\n    if not criterion.candidates:\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/resolvelib/structs.py\", line 156, in __bool__\n    return bool(self._sequence)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py\", line 155, in __bool__\n    return any(self)\n           ^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py\", line 143, in <genexpr>\n    return (c for c in iterator if id(c) not in self._incompatible_ids)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py\", line 44, in _iter_built\n    for version, func in infos:\n  File \"/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/factory.py\", line 297, in iter_index_candidate_infos\n    result = self._finder.find_best_candidate(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py\", line 890, in find_best_candidate\n    candidates = self.find_all_candidates(project_name)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py\", line 831, in find_all_candidates\n    page_candidates = list(page_candidates_it)\n                      ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/index/sources.py\", line 194, in page_candidates\n    yield from self._candidates_from_page(self._link)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py\", line 791, in process_project_url\n    index_response = self._link_collector.fetch_response(project_url)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/index/collector.py\", line 461, in fetch_response\n    return _get_index_content(location, session=self.session)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/index/collector.py\", line 364, in _get_index_content\n    resp = _get_simple_response(url, session=session)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/index/collector.py\", line 135, in _get_simple_response\n    resp = session.get(\n           ^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/requests/sessions.py\", line 602, in get\n    return self.request(\"GET\", url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/network/session.py\", line 520, in request\n    return super().request(method, url, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/requests/sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/requests/sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/cachecontrol/adapter.py\", line 76, in send\n    resp = super().send(request, stream, timeout, verify, cert, proxies)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/requests/adapters.py\", line 538, in send\n    return self.build_response(request, resp)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/cachecontrol/adapter.py\", line 117, in build_response\n    response.read(decode_content=False)\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/urllib3/response.py\", line 560, in read\n    with self._error_catcher():\n  File \"/usr/lib/python3.12/contextlib.py\", line 158, in __exit__\n    self.gen.throw(value)\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/urllib3/response.py\", line 443, in _error_catcher\n    raise ReadTimeoutError(self._pool, None, \"Read timed out.\")\npip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='pypi.org', port=443): Read timed out.\n"
    },
    {
      "file": "services/requirements/api.txt",
      "error": "Traceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/urllib3/response.py\", line 438, in _error_catcher\n    yield\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/urllib3/response.py\", line 561, in read\n    data = self._fp_read(amt) if not fp_closed else b\"\"\n           ^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/urllib3/response.py\", line 527, in _fp_read\n    return self._fp.read(amt) if amt is not None else self._fp.read()\n                                                      ^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/http/client.py\", line 473, in read\n    return self._read_chunked(amt)\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/http/client.py\", line 595, in _read_chunked\n    while (chunk_left := self._get_chunk_left()) is not None:\n                         ^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/http/client.py\", line 579, in _get_chunk_left\n    chunk_left = self._read_next_chunk_size()\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/http/client.py\", line 539, in _read_next_chunk_size\n    line = self.fp.readline(_MAXLINE + 1)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/socket.py\", line 707, in readinto\n    return self._sock.recv_into(b)\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/ssl.py\", line 1252, in recv_into\n    return self.read(nbytes, buffer)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/ssl.py\", line 1104, in read\n    return self._sslobj.read(len, buffer)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTimeoutError: The read operation timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/.local/bin/pip-compile\", line 8, in <module>\n    sys.exit(cli())\n             ^^^^^\n  File \"/usr/lib/python3/dist-packages/click/core.py\", line 1157, in __call__\n    return self.main(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/click/core.py\", line 1078, in main\n    rv = self.invoke(ctx)\n         ^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/click/core.py\", line 1434, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/click/core.py\", line 783, in invoke\n    return __callback(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/click/decorators.py\", line 33, in new_func\n    return f(get_current_context(), *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/.local/lib/python3.12/site-packages/piptools/scripts/compile.py\", line 479, in cli\n    results = resolver.resolve(max_rounds=max_rounds)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/.local/lib/python3.12/site-packages/piptools/resolver.py\", line 635, in resolve\n    is_resolved = self._do_resolve(\n                  ^^^^^^^^^^^^^^^^^\n  File \"/home/runner/.local/lib/python3.12/site-packages/piptools/resolver.py\", line 670, in _do_resolve\n    resolver.resolve(\n  File \"/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py\", line 95, in resolve\n    result = self._result = resolver.resolve(\n                            ^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/resolvelib/resolvers.py\", line 546, in resolve\n    state = resolution.resolve(requirements, max_rounds=max_rounds)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/resolvelib/resolvers.py\", line 397, in resolve\n    self._add_to_criteria(self.state.criteria, r, parent=None)\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/resolvelib/resolvers.py\", line 173, in _add_to_criteria\n    if not criterion.candidates:\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/resolvelib/structs.py\", line 156, in __bool__\n    return bool(self._sequence)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py\", line 155, in __bool__\n    return any(self)\n           ^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py\", line 143, in <genexpr>\n    return (c for c in iterator if id(c) not in self._incompatible_ids)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py\", line 44, in _iter_built\n    for version, func in infos:\n  File \"/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/factory.py\", line 297, in iter_index_candidate_infos\n    result = self._finder.find_best_candidate(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py\", line 890, in find_best_candidate\n    candidates = self.find_all_candidates(project_name)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py\", line 831, in find_all_candidates\n    page_candidates = list(page_candidates_it)\n                      ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/index/sources.py\", line 194, in page_candidates\n    yield from self._candidates_from_page(self._link)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py\", line 791, in process_project_url\n    index_response = self._link_collector.fetch_response(project_url)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/index/collector.py\", line 461, in fetch_response\n    return _get_index_content(location, session=self.session)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/index/collector.py\", line 364, in _get_index_content\n    resp = _get_simple_response(url, session=session)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/index/collector.py\", line 135, in _get_simple_response\n    resp = session.get(\n           ^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/requests/sessions.py\", line 602, in get\n    return self.request(\"GET\", url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/network/session.py\", line 520, in request\n    return super().request(method, url, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/requests/sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/requests/sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/cachecontrol/adapter.py\", line 76, in send\n    resp = super().send(request, stream, timeout, verify, cert, proxies)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/requests/adapters.py\", line 538, in send\n    return self.build_response(request, resp)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/cachecontrol/adapter.py\", line 117, in build_response\n    response.read(decode_content=False)\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/urllib3/response.py\", line 560, in read\n    with self._error_catcher():\n  File \"/usr/lib/python3.12/contextlib.py\", line 158, in __exit__\n    self.gen.throw(value)\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/urllib3/response.py\", line 443, in _error_catcher\n    raise ReadTimeoutError(self._pool, None, \"Read timed out.\")\npip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='pypi.org', port=443): Read timed out.\n"
    },
    {
      "file": "services/requirements/dev.txt",
      "error": "Traceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/urllib3/response.py\", line 438, in _error_catcher\n    yield\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/urllib3/response.py\", line 561, in read\n    data = self._fp_read(amt) if not fp_closed else b\"\"\n           ^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/urllib3/response.py\", line 527, in _fp_read\n    return self._fp.read(amt) if amt is not None else self._fp.read()\n                                                      ^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/http/client.py\", line 473, in read\n    return self._read_chunked(amt)\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/http/client.py\", line 595, in _read_chunked\n    while (chunk_left := self._get_chunk_left()) is not None:\n                         ^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/http/client.py\", line 579, in _get_chunk_left\n    chunk_left = self._read_next_chunk_size()\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/http/client.py\", line 539, in _read_next_chunk_size\n    line = self.fp.readline(_MAXLINE + 1)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/socket.py\", line 707, in readinto\n    return self._sock.recv_into(b)\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/ssl.py\", line 1252, in recv_into\n    return self.read(nbytes, buffer)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/ssl.py\", line 1104, in read\n    return self._sslobj.read(len, buffer)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTimeoutError: The read operation timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/runner/.local/bin/pip-compile\", line 8, in <module>\n    sys.exit(cli())\n             ^^^^^\n  File \"/usr/lib/python3/dist-packages/click/core.py\", line 1157, in __call__\n    return self.main(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/click/core.py\", line 1078, in main\n    rv = self.invoke(ctx)\n         ^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/click/core.py\", line 1434, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/click/core.py\", line 783, in invoke\n    return __callback(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/click/decorators.py\", line 33, in new_func\n    return f(get_current_context(), *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/.local/lib/python3.12/site-packages/piptools/scripts/compile.py\", line 479, in cli\n    results = resolver.resolve(max_rounds=max_rounds)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/.local/lib/python3.12/site-packages/piptools/resolver.py\", line 635, in resolve\n    is_resolved = self._do_resolve(\n                  ^^^^^^^^^^^^^^^^^\n  File \"/home/runner/.local/lib/python3.12/site-packages/piptools/resolver.py\", line 670, in _do_resolve\n    resolver.resolve(\n  File \"/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py\", line 95, in resolve\n    result = self._result = resolver.resolve(\n                            ^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/resolvelib/resolvers.py\", line 546, in resolve\n    state = resolution.resolve(requirements, max_rounds=max_rounds)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/resolvelib/resolvers.py\", line 397, in resolve\n    self._add_to_criteria(self.state.criteria, r, parent=None)\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/resolvelib/resolvers.py\", line 173, in _add_to_criteria\n    if not criterion.candidates:\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/resolvelib/structs.py\", line 156, in __bool__\n    return bool(self._sequence)\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py\", line 155, in __bool__\n    return any(self)\n           ^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py\", line 143, in <genexpr>\n    return (c for c in iterator if id(c) not in self._incompatible_ids)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py\", line 44, in _iter_built\n    for version, func in infos:\n  File \"/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/factory.py\", line 297, in iter_index_candidate_infos\n    result = self._finder.find_best_candidate(\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py\", line 890, in find_best_candidate\n    candidates = self.find_all_candidates(project_name)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py\", line 831, in find_all_candidates\n    page_candidates = list(page_candidates_it)\n                      ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/index/sources.py\", line 194, in page_candidates\n    yield from self._candidates_from_page(self._link)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py\", line 791, in process_project_url\n    index_response = self._link_collector.fetch_response(project_url)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/index/collector.py\", line 461, in fetch_response\n    return _get_index_content(location, session=self.session)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/index/collector.py\", line 364, in _get_index_content\n    resp = _get_simple_response(url, session=session)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/index/collector.py\", line 135, in _get_simple_response\n    resp = session.get(\n           ^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/requests/sessions.py\", line 602, in get\n    return self.request(\"GET\", url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_internal/network/session.py\", line 520, in request\n    return super().request(method, url, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/requests/sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/requests/sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/cachecontrol/adapter.py\", line 76, in send\n    resp = super().send(request, stream, timeout, verify, cert, proxies)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/requests/adapters.py\", line 538, in send\n    return self.build_response(request, resp)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/cachecontrol/adapter.py\", line 117, in build_response\n    response.read(decode_content=False)\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/urllib3/response.py\", line 560, in read\n    with self._error_catcher():\n  File \"/usr/lib/python3.12/contextlib.py\", line 158, in __exit__\n    self.gen.throw(value)\n  File \"/usr/lib/python3/dist-packages/pip/_vendor/urllib3/response.py\", line 443, in _error_catcher\n    raise ReadTimeoutError(self._pool, None, \"Read timed out.\")\npip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='pypi.org', port=443): Read timed out.\n"
    }
  ]
}